name: commit
on: push
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      - name: Build with maturin (non-macOS)
        if: runner.os != 'macOS'
        run: |
          cd python/pyxet
          maturin build -r
      - name: Build with maturin (macOS)
        if: runner.os == 'macOS'
        run: |
          export CXXFLAGS="-stdlib=libc++"
          cd python/pyxet
          rustup target add aarch64-apple-darwin
          maturin build --target universal2-apple-darwin -r
      - name: Unit and integration tests (non-Windows)
        if: runner.os != 'Windows'
        run: |
          cd python/pyxet
          pip install -r tests/requirements.txt
          pip install target/wheels/pyxet*.whl
          pytest tests
      - name: Unit and integration tests (Windows)
        if: runner.os == 'Windows'
        run: |
          cd python/pyxet
          pip install -r tests/requirements.txt
          Get-ChildItem "target/wheels" -Filter pyxet*.whl | Foreach-Object {
            pip install $_.FullName
          }
          pytest tests
