name: commit
on: push
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      - name: Build with maturin (non-macOS)
        if: runner.os != 'macOS'
        run: |
          cd python/pyxet
          maturin build
      - name: Build with maturin (macOS)
        if: runner.os == 'macOS'
        run: |
          export CXXFLAGS="-stdlib=libc++"
          cd python/pyxet
          maturin build